# Generated by Django 5.1.5 on 2025-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('products_items', models.JSONField(default=list)),
            ],
        ),
    ]
