# Generated by Django 5.1.5 on 2025-02-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0002_order_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_list',
            new_name='Order_products',
        ),
        migrations.RenameField(
            model_name='order_products',
            old_name='products_items',
            new_name='product_items',
        ),
    ]
