# Generated by Django 5.1.5 on 2025-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0003_rename_order_list_order_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='permanent_adress',
            field=models.TextField(blank=True),
        ),
    ]
