# Generated by Django 5.1.5 on 2025-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0003_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_products',
            name='adress',
            field=models.JSONField(default=dict),
        ),
    ]
