# Generated by Django 5.1.5 on 2025-02-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0004_customer_permanent_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
