# Generated by Django 5.1.5 on 2025-03-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0004_order_products_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_products',
            name='adress',
        ),
    ]
