# Generated by Django 5.1.5 on 2025-02-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0005_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
