# Generated by Django 5.1.5 on 2025-03-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0005_remove_order_products_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
