# Generated by Django 5.1.5 on 2025-02-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0006_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
