# Generated by Django 5.1.5 on 2025-02-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0007_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
