# Generated by Django 5.1.5 on 2025-02-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0008_alter_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
