# Generated by Django 5.1.5 on 2025-03-03 23:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0008_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
