# Generated by Django 5.1.5 on 2025-03-05 00:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0009_alter_product_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/djedeaw0l/image/upload/v1740995374/profile_fub4k1.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
