# Generated by Django 5.1.5 on 2025-02-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0010_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
