# Generated by Django 5.1.5 on 2025-03-08 19:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0010_alter_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
