# Generated by Django 5.1.5 on 2025-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0011_slider_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_add',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
