# Generated by Django 5.1.5 on 2025-02-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0011_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product_discount',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product_offer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
