# Generated by Django 5.1.5 on 2025-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0012_slider_add_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='product_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
