# Generated by Django 5.1.5 on 2025-02-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0012_administrator_alter_product_list_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='http://127.0.0.1:8000/media/product_images/profile.jpg', upload_to='media/'),
        ),
    ]
