# Generated by Django 5.1.5 on 2025-03-18 07:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0013_alter_product_list_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_add',
            name='slider_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
