# Generated by Django 5.1.5 on 2025-02-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0014_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='media/profile.jpg', upload_to='media/'),
        ),
    ]
