# Generated by Django 5.1.5 on 2025-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0014_alter_slider_add_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_products',
            name='product_items',
            field=models.JSONField(default=dict),
        ),
    ]
