# Generated by Django 5.1.5 on 2025-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0015_alter_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
