# Generated by Django 5.1.5 on 2025-02-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0016_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='permanent_adress',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
