# Generated by Django 5.1.5 on 2025-02-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0017_remove_customer_permanent_adress_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='profile.jpg', upload_to='media/'),
        ),
    ]
