# Generated by Django 5.1.5 on 2025-02-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailapp', '0018_alter_customer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
